version: "3.8"
services:
  builder:
    build: .
    network_mode: bridge
    ports:
      - 6688:6688
    volumes:
      - ./docker/config:/epghub/config
      - ./docker/web:/epghub/web
    environment:
      - XMLTV_URL=http://localhost:6688/epg.xml # Don't touch!
      - TZ=Asia/Shanghai
      - CRON_TRIGGER=0 1,4 * * *
      - PORT=6688
    restart: unless-stopped