version: "3.8"
services:
  server:
    image: nginx
    ports:
      - 88:80
    volumes:
      - ./docker/web:/www
      - ./config/epg.example.conf:/etc/nginx/conf.d/default.conf
  builder:
    build: .
    volumes:
      - ./docker/config:/epghub/config
      - ./docker/web:/epghub/web
    environment:
      - XMLTV_URL=http://server/epg.xml # Don't touch!
      - TZ=Asia/Shanghai
      - CRON_TRIGGER=0 1 * * *
