version: "3.8"
services:
  devcontainer:
    build: .
    network_mode: bridge
    volumes:
      - ../..:/workspaces:cached
    environment:
      - XMLTV_URL=http://127.0.0.1:8788/epg.xml # Don't touch!
      - TZ=Asia/Shanghai
      - CRON_TRIGGER=0 1,4 * * *
      - PORT=8788
    command: sleep infinity
